{% set version = "3.12.0" %}

package:
  name: pymongo
  version: {{ version }}

source:
  url: https://github.com/mongodb/mongo-python-driver/archive/{{ version }}.tar.gz
  sha256: c03817fefb4fd36e6bd695525794ec80419d5bd1b577b6ec8ec9957e98f42285

build:
  number: 0
  script: python -m pip install . -vv
  # Three tests seem to fail on PPC64LE and PyPy
  # test_monitoring test_gridfs_spec test_legacy_api
  script_env:
    - python_impl
    - target_platform

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
  run:
    - python

test:
  source_files:
    - .
  files:
    - run_the_tests.sh
  imports:
    - bson
    - gridfs
    - pymongo
  requires:
    - mongodb     # [not win]
    - setuptools  # [not win]
    - pip
  commands:
    - bash run_the_tests.sh  # [unix and not (ppc64le and python_impl=='pypy')]
    - pip check

about:
  home: https://github.com/mongodb/mongo-python-driver
  license: Apache-2.0
  license_file: LICENSE
  summary: Python driver for MongoDB http://www.mongodb.org

extra:
  recipe-maintainers:
    - licode
    - tacaswell
    - CJ-Wright
    - jan-janssen
